month: August

savings:
  bank: 10000.0
  fgts: 10000.0
  cashback: 200.0

gains:
  taxables:
    - { key: 'salary', value: 10000.0 }
  non_taxables:
    - { key: 'vr/va', value: 1282.0 }

spents:
  debits:
    - { key: 'aluguel', value: 1100.0 }
    - { key: 'condominio', value: 0.0 }
    - { key: 'IPTU', value: 28.58 }
    - { key: 'internet', value: 39.95 }
    - { key: 'healthy', value: 600.0 }
    - { key: 'energy', value: 125 }
  credits:
    - { key: 'spotify', value: 34.9 }
    - { key: 'netflix', value: 55.9 }
    - { key: 'meli 6', value: 19.46 }
    - { key: 'tim beta', value: 60.0 }
    - { key: 'hbo max', value: 13.95 }
    - { key: 'remedios', value: 300 }
  credit_total: 2900.0